### ISSUE TITLE
Does this work with API based orders?

### ISSUE THREAD

**Issue by amjad** [claudiosanches/reduce-stock-of-manual-orders-for-woocommerce#1]
Hello, 

Does this work with API based orders as well?

**Comment by claudiosanches** [comment]
Only orders created on wp-admin.

**Comment by amjad** [comment]
@claudiosanches do you think you will be able to extend it to work with API's (new and legacy)?

**Comment by claudiosanches** [comment]
No, as the plugin name says "Manual orders".
