### ISSUE TITLE
Stock not returning after updating to WooCommerce 3.0.7

### ISSUE THREAD

**Issue by TuureKaunisto** [claudiosanches/reduce-stock-of-manual-orders-for-woocommerce#2]
Hi!

Thanks for the great plugin!

We just updated to WC 3.0.7 and now when we change an order from Completed to Cancelled it no longer returns the cancelled order to the stock level. Otherwise the plugin seems to work just fine and stock levels are reduced when orders are made in the admin.

**Comment by claudiosanches** [comment]
Thanks for your help, I fixed it already in version 2.0.0.
