### ISSUE TITLE
Stock is reduced twice

### ISSUE THREAD

**Issue by jebbdomingo** [claudiosanches/reduce-stock-of-manual-orders-for-woocommerce#5]
It reduces stock when an order status is changed to `Processing` and it reduces again when the order status is changed from `Processing` to `Completed`

**Comment by bedengler** [comment]
I can confirm that. It even reduces the stock twice on orders from the website. So as soon as somebody makes an order, the stock gets reduced twice. For this reason this plugin is useless for now...

**Comment by alexminza** [comment]
@claudiosanches It seems that the check for the _order_stock_reduced post meta does not properly cast booleans:

Value in the database: `_order_stock_reduced = yes`
Check logic in code: `'1' === get_post_meta( $order_id, '_order_stock_reduced', true )`

**Comment by alexminza** [comment]
@claudiosanches there are 2 PR with potential fixes to this critical bug: https://github.com/claudiosanches/reduce-stock-of-manual-orders-for-woocommerce/pulls

**Comment by dolaghan** [comment]
Is there a download of a current completde build available anywhere?
